baseURL = "https://examplesite.com"
googleAnalytics = ""
theme = "omega"
title = "ICP"
[markup.goldmark.renderer]
unsafe = true
[[menu.main]]
name = "Home"
pre = ""
url = "/"
weight = 1
[[menu.main]]
name = "About"
pre = "#"
url = "mission"
weight = 2
[[menu.main]]
name = "Department"
pre = "#"
url = "products"
weight = 3
[[menu.main]]
name = "Join us"
pre = ""
url = "career"
weight = 4
[[menu.main]]
name = "Instagram"
url = "https://www.instagram.com/icpnagoya/"
weight = ""
[[menu.main]]
name = "Twitter"
pre = ""
url = "https://twitter.com/icpnagoya"
weight = ""
[[menu.main]]
name = "Facebook"
pre = ""
url = "https://www.facebook.com/ICPNagoya/"
weight = ""
[params]
author = "Themefisher"
contact_info = "ICP Nagoya <br>International communication party, <br>Japan"
description = "This is meta description"
logo = "images/icplogo.png"
logo_width = "120px"
preloader = true
[params.cookies]
enable = true
expire_days = 2
[params.map]
enable = true
gmap_api = ""
map_center_lat = ""
map_center_lng = ""
map_marker = "images/map-marker.png"
map_position_lat = ""
map_position_lng = ""
[[params.social]]
icon = "fa-twitter"
link = "https://twitter.com/icpnagoya"
title = "twitter"
[[params.social]]
icon = "fa-instagram"
link = "https://www.instagram.com/icpnagoya/"
title = "instagram"
[[params.social]]
icon = "fa-facebook"
link = "https://www.facebook.com/ICPNagoya/"
title = "facebook"
